version: '2.1'
services:
  app:
    build:
        context: ./php-apache/
    container_name: "app"
    working_dir: /var/www/html
    ports:
      - '80:80'
    volumes:
      - ./docs:/var/www/html
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    container_name: 'db'
    command: mysqld --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  mysql-data:
